///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PlacesModelResultsOpeningHours {
/*
{
  "open_now": false
} 
*/

  bool? openNow;

  PlacesModelResultsOpeningHours({
    this.openNow,
  });
  PlacesModelResultsOpeningHours.fromJson(Map<String, dynamic> json) {
    openNow = json["open_now"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["open_now"] = openNow;
    return data;
  }
}

class PlacesModelResultsGeometryLocation {
/*
{
  "lat": 33.9992267,
  "lng": 71.48415290000001
} 
*/

  double? lat;
  double? lng;

  PlacesModelResultsGeometryLocation({
    this.lat,
    this.lng,
  });
  PlacesModelResultsGeometryLocation.fromJson(Map<String, dynamic> json) {
    lat = json["lat"]?.toDouble();
    lng = json["lng"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["lat"] = lat;
    data["lng"] = lng;
    return data;
  }
}

class PlacesModelResultsGeometry {
/*
{
  "location": {
    "lat": 33.9992267,
    "lng": 71.48415290000001
  },
 
} 
*/

  PlacesModelResultsGeometryLocation? location;

  PlacesModelResultsGeometry({
    this.location,
  });
  PlacesModelResultsGeometry.fromJson(Map<String, dynamic> json) {
    location = (json["location"] != null)
        ? PlacesModelResultsGeometryLocation.fromJson(json["location"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (location != null) {
      data["location"] = location!.toJson();
    }

    return data;
  }
}

class PlacesModelResults {
/*
{
  "business_status": "OPERATIONAL",
  "geometry": {
    "location": {
      "lat": 33.9992267,
      "lng": 71.48415290000001
    },
   
  },
  "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/hospital-71.png",
  "icon_background_color": "#F88181",
  "icon_mask_base_uri": "https://maps.gstatic.com/mapfiles/place_api/icons/v2/hospital-H_pinlet",
  "name": "Khyber Dentistry Hospital",
  "opening_hours": {
    "open_now": false
  },
  
  "rating": 3.4,
  
  "user_ratings_total": 5,
  "vicinity": "XFXM+MMR, Rahat Abad, Peshawar"
} 
*/

  PlacesModelResultsGeometry? geometry;
  String? icon;
  String? iconBackgroundColor;
  String? iconMaskBaseUri;
  String? name;
  PlacesModelResultsOpeningHours? openingHours;

  double? rating;

  int? userRatingsTotal;
  String? vicinity;

  PlacesModelResults({
    this.geometry,
    this.icon,
    this.iconBackgroundColor,
    this.iconMaskBaseUri,
    this.name,
    this.openingHours,
    this.rating,
    this.userRatingsTotal,
    this.vicinity,
  });
  PlacesModelResults.fromJson(Map<String, dynamic> json) {
    geometry = (json["geometry"] != null)
        ? PlacesModelResultsGeometry.fromJson(json["geometry"])
        : null;
    icon = json["icon"]?.toString();
    iconBackgroundColor = json["icon_background_color"]?.toString();
    iconMaskBaseUri = json["icon_mask_base_uri"]?.toString();
    name = json["name"]?.toString();
    openingHours = (json["opening_hours"] != null)
        ? PlacesModelResultsOpeningHours.fromJson(json["opening_hours"])
        : null;

    rating = json["rating"]?.toDouble();

    userRatingsTotal = json["user_ratings_total"]?.toInt();
    vicinity = json["vicinity"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();

    if (geometry != null) {
      data["geometry"] = geometry!.toJson();
    }
    data["icon"] = icon;
    data["icon_background_color"] = iconBackgroundColor;
    data["icon_mask_base_uri"] = iconMaskBaseUri;
    data["name"] = name;
    if (openingHours != null) {
      data["opening_hours"] = openingHours!.toJson();
    }

    data["rating"] = rating;

    data["user_ratings_total"] = userRatingsTotal;
    data["vicinity"] = vicinity;
    return data;
  }
}

class PlacesModel {
/*
{
 
  
  "results": [
    {
      
      "geometry": {
        "location": {
          "lat": 33.9992267,
          "lng": 71.48415290000001
        },
        
      },
      "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/hospital-71.png",
      "icon_background_color": "#F88181",
      "icon_mask_base_uri": "https://maps.gstatic.com/mapfiles/place_api/icons/v2/hospital-H_pinlet",
      "name": "Khyber Dentistry Hospital",
      "opening_hours": {
        "open_now": false
      },
     
      "rating": 3.4,
     
      "user_ratings_total": 5,
      "vicinity": "XFXM+MMR, Rahat Abad, Peshawar"
    }
  ],
  "status": "OK"
} 
*/

  List<PlacesModelResults?>? results;
  String? status;

  PlacesModel({
    this.results,
    this.status,
  });
  PlacesModel.fromJson(Map<String, dynamic> json) {
    if (json["results"] != null) {
      final v = json["results"];
      final arr0 = <PlacesModelResults>[];
      v.forEach((v) {
        arr0.add(PlacesModelResults.fromJson(v));
      });
      results = arr0;
    }
    status = json["status"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();

    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["results"] = arr0;
    }
    data["status"] = status;
    return data;
  }
}
